### ISSUE TITLE
Timeouts

### ISSUE THREAD

**Issue by thomaskien** [iZettle/URL-Scheme#10]
Please add timeouts, there are none (I waited some minutes) therefore everything stands still in an undefined state (view of our main-system) – e.g. if there is a fatal error it should be returned imediately via return-code.

or there should be a option to configure the behaviour: e.g. returncode-only...

**Comment by mattiasjahnke** [comment]
Hi,

Not sure what you mean. The iZettle payment flow will present the user with an error message in case of a failure and there is usually a button for the user to tap in order to cancel the flow and return to the calling app.

What's the scenario for a timeout?

**Comment by mattiasjahnke** [comment]
Sorry, didn't see that this question was asked over 2 year ago ;) Closing
