### ISSUE TITLE
No parameters is working for me, why?

### ISSUE THREAD

**Issue by clinton4** [iZettle/URL-Scheme#14]
Hi There,

When i create a link like this:
```
<a href="izettle://payment/charge?amount=100&currency=NOK&reference=test">My link text</a>
```

The iZettle app is beeing opended, but the amount 100 is not displaying at all.

What am i doing wrong?

**Comment by jensutbult** [comment]
Can you please provide a screen dump of the issue?

**Comment by clinton4** [comment]
Here is a video:
https://youtu.be/SOBfJhY697o

**Comment by jensutbult** [comment]
I'm sorry but the URL scheme is only available on iOS at the moment.
