### ISSUE TITLE
URL-scheme broken on iOS9?

### ISSUE THREAD

**Issue by Jaspur** [iZettle/URL-Scheme#16]
I have an iPhone where I tried the following: izettle://api/payment/charge?amount=20.10
That didn’t open the app with the amount already there as expected. Just plain opened the app, thats it.

![b8b464cb-76ab-4922-bbf4-ccc80cf5be05](https://cloud.githubusercontent.com/assets/4254854/11339481/050e3620-91fa-11e5-8a38-3936e461c95d.png)

**Comment by mattiasjahnke** [comment]
Hey @Jaspur 

Seems like you're missing the `successURL` and `failureURL` (https://github.com/iZettle/URL-Scheme#protocol-introduction).
