### ISSUE TITLE
APP-Persistence

### ISSUE THREAD

**Issue by thomaskien** [iZettle/URL-Scheme#9]
After each payment the app is waiting for a OK toch and there is no timeout... but the sucess is submitted of course afterwards – that’s not good. Our system is waiting for the payment to process the following e.g. print jobs, and everything hangs on a OK to touch. 

Sure you like your app, but you earn money with payments ---> there should be a silent-option to only perform the absolutely-necessary interaction with no need to swipe and touch unnecessarily, or that option should be enabled automatically if a e-mail is provided (see last suggestion)

In my opinion the Pin & card reader should be the only thing which needs to be touched after the payment is initialized...

**Comment by mattiasjahnke** [comment]
Hi @thomaskien 

After a payment is initiated with the URL scheme, there are no other interactions in the app given that:
* There are no errors
* The card doesn't require a signature from the customer

**Comment by mattiasjahnke** [comment]
Sorry, didn't see that this question was asked over 2 year ago ;) Closing

**Comment by thomaskien** [comment]
Hi Mattias!

I explain it to you anyway :-) If you keep the izettle-device in a drawer using the brutal way of integration (safari refreshes every 5 seconds, if payment wanted php page refreshes to izettle:// url after payment initiated via regular PC). 
in case of payment error you need to get the device physically to push one button in order to get the device to work again for next payment if there is no timeout.

We are using this setup now for about 2 years with only few problems, but in fact this issue never turned out to be a problem - people generally know the pin ;-)

Regards,

Thomas
